### PR TITLE
add ${DESTDIR} variable to Makefile

### PR DESCRIPTION
**Pull request by ClayStan**
add ${DESTDIR} variable to un/install target in Makefile.
In order to follow the GNU coding standard : https://www.gnu.org/prep/standards/html_node/DESTDIR.html.
I'm a Debian Contributor, I'm going to package this project to push to Debian.

### CODE REVIEW

**Review by ClayStan — COMMENTED** [review]
Remove the wrong executable permissions from the C source code file

**Comment by Dr-Noob** [comment]
Hi,

Thank you very much for your PR. I would be so happy to see cpufetch as a package in Debian. You are right about the standard, I chose PREFIX but it didn't make much sense.

I have pushed a commit to master in which I replaced PREFIX with DESTDIR, instead of keeping both. I also updated the Arch Linux package. I'm closing this PR but please let me know if you need any further changes to build the package properly. I would appreciate a message whenever the package gets included in Debian, I would like to give it a try.

Thanks!

**Comment by ClayStan** [comment]
> Hi,
> 
> Thank you very much for your PR. I would be so happy to see cpufetch as a package in Debian. You are right about the standard, I chose PREFIX but it didn't make much sense.

I suggest  don't remove PREFIX, DESTDIR can't replace PREFIX, The debian packaging script will set $(DESTDIR) to the temporary directory : https://www.debian.org/doc/manuals/maint-guide/modify.en.html 
We should define PREFIX ?= /usr, and then add the DESTDIR but don't define by ourselves
you can look my this commit: https://github.com/ClayStan/cpufetch/commit/dc1e2067c6ca14c87cb499ba292d666c65ef4470

and a small suggest, add  ' -f ' parameter in Makefile clean target: https://github.com/ClayStan/cpufetch/commit/698a9141714615fa94734d414fe3f44eb6ca6f3e

> 
> I have pushed a commit to master in which I replaced PREFIX with DESTDIR, instead of keeping both. I also updated the Arch Linux package. I'm closing this PR but please let me know if you need any further changes to build the package properly. I would appreciate a message whenever the package gets included in Debian, I would like to give it a try.

when this package gets included in Debian, I'll tell you.
:)

> 
> Thanks!

**Comment by Dr-Noob** [comment]
Ok, so I have pushed a commit (4023afb) to `bugfix` branch (will merge when we are sure that everything is ok) to update the Makefile according to your instructions.

Don't we need to add/remove some compilation flags? I think that the ideal would be to compile with `-O3`. I have it in release target, but I don't think that you like the `-static`. Maybe I could change that to two different targets:

release: `-O3`
static: `-O3 -static`

What do you think?

**Comment by ClayStan** [comment]
> Ok, so I have pushed a commit ([4023afb](https://github.com/Dr-Noob/cpufetch/commit/4023afb95f9990be3f0a3148cddd338995d0a5c8)) to `bugfix` branch (will merge when we are sure that everything is ok) to update the Makefile according to your instructions.
> 
> Don't we need to add/remove some compilation flags? I think that the ideal would be to compile with `-O3`. I have it in release target, but I don't think that you like the `-static`. Maybe I could change that to two different targets:
> 
> release: `-O3`
> static: `-O3 -static`
> 
> What do you think?

hmm...
For debian, the package scripts will set them by default, so debian need't these flags.
But if you want, or want to use it for others people/distributions, you can also set it

**Comment by ClayStan** [comment]
And a new issue
I notice have a manpage in your source code: cpufetch.8 :https://github.com/Dr-Noob/cpufetch/blob/master/cpufetch.8
But in the official definition of manpage section, 8 means " System management commands" :
“Commands like mount(8), many of which only root can execute.”

I think 1 is more appropriate, 1 means User commands (Programs) : Commands that can be executed by the user from within a
shell.
suggest rename cpufetch.8 to cpufetch.1

have a look:
https://www.man7.org/linux/man-pages/man7/man-pages.7.html
https://en.wikipedia.org/wiki/Man_page
https://www.cyberciti.biz/faq/howto-use-linux-unix-man-pages/

**Comment by Dr-Noob** [comment]
You are totally right about the number of the manpage. Thanks!

I have changed it to 1, and also pushed the new Makefile to master, with the optimization flags by default, and with PREFIX and DESTDIR.

**Comment by coldtobi** [comment]
Hi, 
first thanks for cpufetch!

I've been brought here when reviewing  @ClayStan's package for Debian; 
let me give some remarks for the Makefile, with some focus on Debian:

- please append $CFLAGS to your CFLAGS. Debian will set some default compiler flags and a package should not override them.  This allows you to have e.g your preferred optimization while Debian can easily set its own preferred level. (Just an example; another one would be automatic debug symbol packages or the reproducible builds project)
- Note that "-Werror" can be very fragile when building for distributions: We often introduce newer compilers etc. and it is PITA
if that makes a package break just because diagnostics got better…
- (It is possibly also a good idea not to have a hard override to CC; better would be to CC?=)

Cheers, tobi

**Comment by Dr-Noob** [comment]
Hi @coldtobi, thanks for your help!

I have little experience with packaging so I appreciate any suggestions, and I found yours pretty adequate. Please let me know if you find any other things to fix/improve

PS: Now that I have appended CFLAGS, I have found that in Arch package, it ends up compiling with -O2 (set by Arch) and -O3 (set by me). I suspect that this could happen in other distros too. Should I remove the optimization flags in the Makefile and expect those flags to be set by the distribution?

**Comment by coldtobi** [comment]
> PS: Now that I have appended CFLAGS, I have found that in Arch package, it ends up compiling with -O2 (set by Arch) and -O3 (set by me). I suspect that this could happen in other distros too. Should I remove the optimization flags in the Makefile and expect those flags to be set by the distribution?

mmm.. I'd leave it to the distributions, or use something like CFLAGS= <my cflags…> $$CFLAGS, so that your settings wont  override the distributions ones. 

Another, more intrusive idea, would be to switch to something that generates the Makefiles for you; I've got good experience with CMake… There is a lot of knowledge in it when it comes to portability and build profiles and will help going… (Its default settings are usually 95% fine, but some things needs to be considered as well; to be distribution friendly, I could expand if you thinking that direction could work for you.)

**Comment by ClayStan** [comment]
Hey, bro @Dr-Noob 
Can u update the "what's entry" section in manpage,
"manual page for cpufetch v0.97 (x86_64 build)"  like a template, and will get a lintian warning:https://lintian.debian.org/tags/useless-whatis-entry

can u update it like this
2021-06-11 15-53-38 的屏幕截图
Then gen a new tag.

**Comment by Dr-Noob** [comment]
Hi @ClayStan, thanks for the suggestion, I've just pushed the changes to (hopefully) avoid the lintian warning. When you mean to generate a new tag, you mean a git tag, right? Is strictly necessary to do this, or can you upload the package with a new tag?

**Comment by ClayStan** [comment]
> Hi @ClayStan, thanks for the suggestion, I've just pushed the changes to (hopefully) avoid the lintian warning. When you mean to generate a new tag, you mean a git tag, right?

Yeah, we need a new git tag for upload to debian.

> Is strictly necessary to do this, or can you upload the package with a new tag?

**Comment by Dr-Noob** [comment]
I just created a new tag (`v0.98`). Let me know if you need anything else.

**Comment by Dr-Noob** [comment]
@ClayStan Any news on the debian package? I'm closing the pull request but feel free to keep comenting.

**Comment by ClayStan** [comment]
> @ClayStan Any news on the debian package? I'm closing the pull request but feel free to keep comenting.

Package has been put into the NEW queue
Thanks for @coldtobi  Sponsor
https://ftp-master.debian.org/new.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986783

**Pull request closed without merging**
